name: pet_management_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.0-198.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus: ^2.2.0
  get: ^4.7.2
  intl: ^0.20.2
  path: ^1.9.1
  sizer: ^3.1.3
  sqflite:
    ^2.4.2
    # Launcher & Splash
  flutter_native_splash: ^2.3.5
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#9C27B0"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

# Native Splash Screen Configuration
flutter_native_splash:
  color: "#9C27B0"
  image: assets/images/splash_icon.png
  color_dark: "#1A1A1A"
  image_dark: assets/images/splash_icon.png
  android_12:
    icon_background_color: "#9C27B0"
    image: assets/images/splash_icon.png
  android: true
  ios: true
  web: false
