name: pesty
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-198.0.dev

dependencies:
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  flutter:
    sdk: flutter
  get: ^4.7.2
  google_sign_in: ^7.2.0
  intl: ^0.20.2
  path: ^1.9.1
  shared_preferences: ^2.5.3
  sign_in_with_apple: ^7.0.1
  sizer: ^3.1.3
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
